---
driver:
  name: docker

platforms:
  - name: debian13
    image: "geerlingguy/docker-debian13-ansible:latest"
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
      - /var/lib/containerd
    cgroupns_mode: host
    privileged: true
    pre_build_image: true

lint: |
  set -e
  yamllint .
  ansible-lint

provisioner:
  name: ansible
  ansible_args:
    - --diff
  become: true
